version: '3'
services:
  client_1:
    container_name: chat-client_1
    tty: true
    build: ./
    volumes:
      - ./:/go/src/app
  client_2:
    container_name: chat-client_2
    tty: true
    build: ./
    volumes:
      - ./:/go/src/app

networks:
  default:
    external:
      name: clichat_network_1